name: react-weather-gcp-deploy
run-name: ${{ github.actor }} is deploying react-weather
on: [push]
jobs:
  deploy-to-google-app-engine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: adam-workshop
          export_default_credentials: true

      - name: Install beta components
        run: gcloud components install beta

      - name: Deploy to Google App Engine
        run: gcloud app deploy --quiet
